# **Sample pretreatment for nontarget and suspect screening** {#SamplePretreatment}

<br><br>


## Accelerated solvent extraction (ASE)

https://tools.thermofisher.com/content/sfs/brochures/36395-TN209_V28_releasedJC042606.pdf  
http://apps.thermoscientific.com/media/cmd/rafa2013/13%20Galbiatti%20RAFA%202013.pdf  

In some samples containing moisture or water such as soil samples or food samples (animal tissue, fruits, vegetables, and so on) an additional step may be needed either before the extraction step or as a post extraction step to remove the moisture. Sample drying can be accomplished in several ways such as air drying and oven drying prior to extraction. However, these approaches are not suited when analyzing volatile or semi-volatile components as they would be removed from the sample prior to extraction or analysis.
Another common method for moisture removal is by using salts such as sodium sulfate, calcium chloride, magnesium sulfate, calcium sulfate and the like. These salts tend to associate to water molecules to form hydrated salts. Sodium sulfate for example tends to clump together when water is present.  
Sodium sulfate is not suitable for in-cell moisture removal and accelerated solvent extraction. Sodium sulfate can dissolve in hot solvent to a certain extent and can precipitate downstream in some instances clogging the outlet frit, tubes and valves. Moreover, sodium sulfate becomes an aggregate hard lump upon water absorption and is not easy to process during sample preparation for in-cell moisture removal and extraction.
  
## Ultrasonic extraction


## Direct injection using Large Volume Injection

https://www.chromatographyonline.com/view/large-volume-injection-lc-ms-ms-methods-aqueous-samples-and-organic-extracts

https://www.sciencedirect.com/science/article/pii/S0045653520331581?via%3Dihub

https://enveurope.springeropen.com/articles/10.1186/s12302-023-00779-4:
The high sensitivity of the current generations of LC–HRMS equipment allows for direct injection (DI) of water samples without any enrichment steps. The advantages of DI are the small water volumes required, low efforts with sample processing and less risk of background contamination during sample preparation. Minimising the sample processing results in negligible losses of compounds, as each manipulation step may discriminate against substances (e.g., by evaporation, precipitation or degradation). To obtain a sufficient sensitivity, typically large volume injections are used for DI, with volumes of 100 [26], 250 [27] or up to 650 µL [28], as no further enrichment of the sample takes place. In such cases, an adjustment of the sample composition before injection by adjusting pH and solvent addition is necessary to avoid phase dewetting or injection solvent mismatch (see Sect. “Choice of separation method”). A direct preparation of sub-samples for analysis is possible in the field by transferring individual aliquots of 1 mL into autosampler vials from a larger sampling vessel. Depending on the load of suspended particulate matter, settling of particles before aliquoting alone may be sufficient; alternatively, a filtration or centrifugation step might be necessary before analysis, with the accompanying risk of compound losses. A drawback of DI is the potential contamination of the ion source with inorganic salts that would be removed by SPE or liquid–liquid extraction (LLE). This is particularly critical for samples from estuarine or marine environments, for which even a diversion of the eluent flow away from the ion source at early retention times (RT) might not be sufficient.

  





