# **Suspect screening** {#suspect_screening}

<br><br>


## HRMS spectra library setup
1.	Copy the template excel sheet for your analytical run (LC, GC, ESI, EI, POS, NEG,..) to the ”1_Standard_infosheets” folder.  
2.	The ”Spectral_FileName” cell will autogenerate the name for the msp file based on the filled cells. Copy this file name later for the msp file.  
3.	Open MS-DIAL  
4.	Perform peak peaking,….  
a.	Xxx  
b.	Xxx  
c.	Xxx  
d.	Xxx  
5.	Double click on the individual file at the file navigator (click on the text of the file name)  
6.	In the ”peak spot viewer” find the peak of the standard chemical. Click on the triangle to show the deconvoluted spectrum.  
7.	Retention time index is not exported to MS-FINDER. NEED TO FIX or MANUALLY COPY FROM EXCEL INFO SHEET.    
..  
X. Use LIB2NIST to convert combined msp file to NIST library. NEED TO ADD RETENTIONINDEX in comment
Convert your library list into NIST library format using LIB2NIST command line (in order to preserve the accurate mass). See command line help file for arguments.  
  
COMMAND:  
`lib2nist.exe /log9 Mylib.log /OutLib /StdRounding:N /MsmsOnly:Y /AccuratePeakMZ /PrecurMzDecPlaces=keep /PeakMzDecPlaces=keep /UseSubset:N <path to msp file> <output path> =<new name of library>`  
    
EXAMPLES:  
`lib2nist64.exe /log9 Mylib.log /OutLib /StdRounding:N /MsmsOnly:Y /AccuratePeakMZ /PrecurMzDecPlaces=keep /PeakMzDecPlaces=keep /UseSubset:N D:\Projects\Suspect_lists\Spectral_databases\RECETOX_GC-EI_MS_20201028.msp D:\Program\NIST14\ =RECETOX_GC-EI_MS_20201028`  
  
<br><br><br>



## Listing suspects
<br><br>



## Suspect scoring
<br>
https://www.waters.com/waters/fr_FR/Mass-Accuracy-and-Resolution/nav.htm?locale=fr_FR&cid=10091028
<br>

Mass error (ppm): <br>

\begin{equation} 
  ME_{ppm} = \frac{mz_{theor} - mz_{meas}}{mz_{theor}} * 10^6
\end{equation} <br>

where *mz~theor~* is the theoretical exact mass (in u or Da) of the isotope, and *mz~meas~* is the measured accurate mass from the instrument.

<br>


RMS of isotope mz error ppm: <br>
\begin{equation} 
  RMS_{mz} = \sqrt{\frac{\sum_{i=1}^n (ME_{ppm})^2}{n}}
\end{equation} <br>

At least mz of isotopes M, M+1, M+2 (n > 3) should be included in the calculations to give good estimate of the average 

RMS of isotope intensities (%): <br>
\begin{equation} 
  RMS_{Ab} = \sqrt{\frac{\sum_{i=1}^n (Ab_{theor} - Ab_{meas})^2}{n}}
\end{equation} <br>
