# Example workflow: indoor dust {#example_dust}

A walkthrough for indoor dust analysis

<br><br>  




```{r example_workflows_dust, echo=FALSE, fig.cap= "Workflow for nontarget using XX"}

# Diagrammer: rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html

grViz("
digraph Scheme {
      
# graph statement
graph [layout = dot, overlap = false, rankdir = LR]

# node statements
node [shape = box,
fontname = Helvetica, fontsize = 35, style = filled]
      
node [color = black, fillcolor = white, fixedsize = false]
# A [label = 'Indoor dust collected \\n among different \\n use categories']
# 
# node [color = black, fillcolor = white, fixedsize = false]
# B1 [label = 'Collect different groups']
# B2 [label = 'QA/QC']
# 
# 
# node [color = black, fillcolor = white, fixedsize = false]
# C1 [label = 'Sample different groups']
# C2 [label = 'Suspect list of Cl/Br compounds']

node [color = black, fillcolor = white, fixedsize = false]
D1 [label = 'Sample extraction']
D1_1 [label = 'Hexane 3 mL']
D1_2 [label = 'Hexane: Acetone (1:1) 3 mL']
D1_3 [label = 'Toluene 3 mL']
D2 [label = 'Combine and split 1:1']
D3_1 [label = 'GC']
D3_2 [label = 'LC']
D4 [label = 'split 1:1']



E1 [label = 'GC-HRMS']
E2 [label = 'LC-HRMS']
# 
# 
# node [color = black, fillcolor = white, fixedsize = false]
# F1 [label = 'Suspect screening']
# F2 [label = 'Nontarget']
# 
# G1 [label = 'Mass defect plots']

      
      
# edge statements
edge [color = black]
# A -> {B1}
# B2 -> {C1}
# B1 -> {C1 C2}
# C1 -> {D1}

D1 -> {D1_1}
D1_1 -> {D1_2}
D1_2 -> {D1_3}
D1_1 -> {D2}
D1_2 -> {D2}
D2 -> {D3_1}
D2 -> {D3_2}
D3_1 -> {D4}
D1_3 -> {D4}

D3_2 -> {E2}
D4 -> {E1}
D1_3 -> {E1}
      
      }
      ")


```


```{r data processing, echo=FALSE}

grViz("
digraph Scheme {
      
# graph statement
graph [layout = dot, overlap = false]

# node statements
node [shape = box,
fontname = Helvetica, fontsize = 35, style = filled]
      
node [color = black, fillcolor = white, fixedsize = false]

ZERO [label = 'Deconvolution']

A [label = 'Target analysis']
B [label = 'Suspect list screening']

C [label = 'NIST library screening']
C1 [label = 'Molecular ion confirmation']
C2 [label = 'Retention time index']


D [label = 'Mass defect \\n (selected mz, rt and int of annotated compounds']

subgraph cluster2 {
E [label = 'Annotation']
ID1 [label = 'Confirm EIC peaks']
}

F [label = 'Molecular networking']
G [label = 'Multivariate statistics']

ID2 [label = 'Peak/Component list with \\n partial annotation']

Q1 [label = 'Semiquantify across samples']      
      
# edge statements

edge [color = black]

ZERO -> {A B C}
A -> {E}
B -> {E}

{C1 C2} -> {C}
C -> {E}

E -> {ID1}
ID1 -> {ID2}
ID2 -> {F}
ID2 -> {G}
ID2 -> {D}
ID2 -> {Q1}

}
")


```


