# A handbook on GC Q Exactive orbitrap use 



```{r msresolution, echo=FALSE}


MSresolution <- dplyr::tibble(
  Resolution_at_mz200 = c(7500, 15000, 30000, 45000, 60000, 120000, 240000),
  Scan_rate_Hz = c(40, 28, 12, 10, 7, 3, 1.5),
  Transient_lenght_ms = c(16, 32, 64, 96, 128, 256, 512),
  Suggested_max_fill_time_ms = c(11, 20, 50, 86, 110, 240, 500)
)
DT::datatable(MSresolution)


```

Recommended to have about 10-12 scans per peak.
  
  
## Terminologies
  
_Automatic Gain Control (AGC):_ Sets the ion injection time to maintain the optimum quantity of ions for each scan. With AGC on, the scan function consists of a prescan and an analytical scan. The split lens is used to start and stop the injection of ions into the mass analyzer. It provides a high deflection voltage most of the time so that ions are deflected into a baffle except when they are to be allowed into the C-Trap. The fast switching of the ion beam ensures the precise determination of the ion injection time that is required for AGC. This is since if too many ion are in the ion cloud going in to the orbitrap, then it will oversaturate the detector.

_Chemical Ionization (CI):_ Gas flow 

