# A handbook on GC Q Exactive orbitrap use {#GCOrbitrapHandbook}



```{r msresolution, echo=FALSE}


MSresolution <- dplyr::tibble(
  Resolution_at_mz200 = c(7500, 15000, 30000, 45000, 60000, 120000, 240000),
  Scan_rate_Hz = c(40, 28, 12, 10, 7, 3, 1.5),
  Transient_lenght_ms = c(16, 32, 64, 96, 128, 256, 512),
  Suggested_max_fill_time_ms = c(11, 20, 50, 86, 110, 240, 500)
)
DT::datatable(MSresolution)


```

Recommended to have about 10-12 scans per peak.



## Chemical ionization
If the instrument is in CI mode, choose the right Calibration gas and Ionization mode (“CI”), as well as the CI gas flow (typically 1-2), gas port (Port B as of 20210429, actual CI gas flow should indicate the correct port), and gas type (likely Methane, but check the cylinder). Open the CI gas flow at 2ml/min before opening anything else (before the calibration gas, filament, MS), otherwise the flow can be unstable. Afterwards the CI can be adjusted to lower flow 

  
## Terminologies
  
_Automatic Gain Control (AGC):_ Sets the ion injection time to maintain the optimum quantity of ions for each scan. With AGC on, the scan function consists of a prescan and an analytical scan. The split lens is used to start and stop the injection of ions into the mass analyzer. It provides a high deflection voltage most of the time so that ions are deflected into a baffle except when they are to be allowed into the C-Trap. The fast switching of the ion beam ensures the precise determination of the ion injection time that is required for AGC. This is since if too many ion are in the ion cloud going in to the orbitrap, then it will oversaturate the detector.
  
_Chemical Ionization (CI):_ 
  
_Nitrogen gas:_ Nitrogen gas is used for the purging of the ion source when removing the ion volume. It is also used in the C-Trap, when the ions are accumulated and their energy is dampened using a bath gas (nitrogen).



## XCMS preprocessing
Check: A scalable workflow to characterize the human exposome, SI-11, https://www.nature.com/articles/s41467-021-25840-9#MOESM14

IPO optimization


